image: ghcr.io/osscontainertools/kaniko:debug
stages:
  - build-and-push
build-and-push-job:
  stage: build-and-push
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GODEBUG: "http2client=0"
    KUBERNETES_CPU_REQUEST: "4"
    KUBERNETES_MEMORY_REQUEST: "16Gi"
    KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "64Gi"
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.cpu"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
      --cache=false
      --compressed-caching=false
      --push-retry=15