apiVersion: batch/v1
kind: Job
metadata:
  name: frac-bio-embed-train
spec:
  template:
    spec:
      containers:
        - name: train
          image: gitlab-registry.nrp-nautilus.io/rcurrie/frac-bio-embed
          command: ["python", "train.py"]
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 1Gi
              cpu: 1
          args: ["-h"]
      restartPolicy: Never
